name: Build APK

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Android SDK / commandline tools
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0"

      # Use Gradle without cache (avoids cache service outages)
      - name: Setup Gradle (cache disabled)
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-disabled: true

      - name: Build Release APK
        run: |
          gradle --no-daemon --stacktrace assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Kairo-APK
          path: app/build/outputs/apk/release/app-release.apk
