name: Build APK

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components (API 34)
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Setup Gradle (pin 8.7, no cache)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7
          cache-disabled: true

      - name: Build APKs
        run: |
          set -o pipefail
          gradle --no-daemon --stacktrace --warning-mode all assembleRelease 2>&1 | tee build_release.log

      - name: Upload build log
        uses: actions/upload-artifact@v4
        with:
          name: build-logs
          path: build_release.log

      - name: Decode keystore
        run: echo "$KEYSTORE_BASE64" | base64 -d > release.keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Align & Sign release APK
        run: |
          UNSIGNED=app/build/outputs/apk/release/app-release-unsigned.apk
          ALIGNED=app-release-aligned.apk
          SIGNED=Kairo-Launcher-v0.1.0-release-signed.apk

          "${ANDROID_HOME}/build-tools/34.0.0/zipalign" -f -p 4 "$UNSIGNED" "$ALIGNED"
          "${ANDROID_HOME}/build-tools/34.0.0/apksigner" sign \
            --ks release.keystore \
            --ks-key-alias "$KEY_ALIAS" \
            --ks-pass env:STORE_PASSWORD \
            --key-pass env:KEY_PASSWORD \
            --out "$SIGNED" \
            "$ALIGNED"

          "${ANDROID_HOME}/build-tools/34.0.0/apksigner" verify "$SIGNED"
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: Kairo-APK
          path: |
            Kairo-Launcher-v0.1.0-release-signed.apk
            app/build/outputs/apk/debug/*.apk
