name: Build APK

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK components (API 34)
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Setup Gradle (pin 8.7, no cache)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7
          cache-disabled: true

      - name: Build APKs
        run: |
          gradle --no-daemon --stacktrace assembleRelease assembleDebug
          echo "== OUTPUTS ==" && ls -R app/build/outputs || true

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: Kairo-APK
          path: |
            app/build/outputs/apk/release/*.apk
            app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
